### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by mzaini30** [thatKazLX/Instagram-Tools#1]
```
 [?] Try to Login . . .
{ [CookieNotValidError: Cookie `sessionid` you are searching found was either not found or not valid!]
  name: 'CookieNotValidError',
  message: 'Cookie `sessionid` you are searching found was either not found or not valid!' }
```

**Comment by FrancescoConforte** [comment]
Same for me! Could you solve it?

**Comment by mzaini30** [comment]
@FrancescoConforte No. I didn't try it again.

**Comment by alex198555** [comment]
I have the same issues: 

 [?] Try to Login . . .
C:\Users\aorek\Desktop\bot-igeh-master\bot-igeh-master\komenlike.js:72
  const Device = new Client.Device(params.username);
                            ^

TypeError: Cannot read properties of undefined (reading 'Device')
    at doLogin (C:\Users\aorek\Desktop\bot-igeh-master\bot-igeh-master\komenlike.js:72:29)
    at doMain (C:\Users\aorek\Desktop\bot-igeh-master\bot-igeh-master\komenlike.js:119:19)
    at C:\Users\aorek\Desktop\bot-igeh-master\bot-igeh-master\komenlike.js:173:3

**Comment by thatKazLX** [comment]
This tool isn't working anymore.
